
- hosts: ds9its11
  become: true
  become_method: sudo

  tasks:
    - name: git install
      dnf: 
        name: git
        state: present

    - name: podman install
      dnf:
        name: podman
        state: present

    - name: podman module mkdir
      file: 
        state: directory
        path: ~/.ansible/collections/ansible_collections/containers
      become: no

    - name: podman module install
      shell: |
        git clone https://github.com/containers/ansible-podman-collections.git ~/.ansible/collections/ansible_collections/containers/podman
      become: no
