
- hosts: ds9its11
  become: true
  become_method: sudo

  vars:
    pod_path: /data/red-pod{{ env_id }}/
    redmine_name: redmine{{ env_id }}

  tasks:
    - name: common
      block:
        - name: agile confirm {{ redmine_name }}
          stat: path="{{ pod_path }}backup/plugins/redmine_agile-1_6_3-light.zip"
          register: result0

        - name: agile unzip
          unarchive:
            src: "{{ pod_path }}backup/plugins/redmine_agile-1_6_3-light.zip"
            dest: "{{ pod_path }}redmine/plugins/"
          when: result0.stat.exists

          #when: v == "exit"

    - name: Redmine v5.0.0
      block:
        - name: checklists v5 confirm {{ redmine_name }}
          stat: path="{{ pod_path }}backup/plugins/redmine_checklists-3_1_21-light.zip"
          register: result1

        - name: checklists unzip
          unarchive:
            src: "{{ pod_path }}backup/plugins/redmine_checklists-3_1_21-light.zip"
            dest: "{{ pod_path }}redmine/plugins/"
          when: result1.stat.exists

      when: v == "v5"

    - name: Redmine v4.2.5
      block:

        - name: checklists v4 confirm
          stat: path="{{ pod_path }}backup/plugins/redmine_checklists-3_1_19-light.zip"
          register: result1

        - name: checklists unzip
          unarchive:
            src: "{{ pod_path }}backup/plugins/redmine_checklists-3_1_19-light.zip"
            dest: "{{ pod_path }}redmine/plugins/"
          when: result1.stat.exists

#    - name: People plugin confirm
#      stat: path="{{ pod_path }}backup/plugins/redmine_people-1_6_1-light.zip"
#      register: result2

#    - name: People plugin unzip
#      unarchive:
#        src: "{{ pod_path }}backup/plugins/redmine_people-1_6_1-light.zip"
#        dest: "{{ pod_path }}redmine/plugins/"
#      when: result2.stat.exists

        - name: Tags
          ansible.builtin.git:
            repo: https://github.com/ixti/redmine_tags.git
            dest: "{{ pod_path }}/redmine/plugins/redmine_tags"

        - name: Hide Sidebar
          ansible.builtin.git:
            repo: https://gitlab.com/bdemirkir/sidebar_hide.git
            dest: "{{ pod_path }}/redmine/plugins/sidebar_hide"

#    - name: issue template
#      ansible.builtin.git:
#        repo: https://github.com/agileware-jp/redmine_issue_templates.git
#        dest: "{{ pod_path }}/redmine/plugins/redmine_issue_templates"

#    - name: view customize plugin
#      ansible.builtin.git:
#        repo: https://github.com/onozaty/redmine-view-customize.git
#        dest: "{{ pod_path }}/redmine/plugins/view_customize"

        - name: persist wiki format plugin
          ansible.builtin.git:
            repo: https://github.com/pinzolo/redmine_persist_wfmt.git
            dest: "{{ pod_path }}/redmine/plugins/redmine_persist_wfmt"

        - name: hearts plugin
          ansible.builtin.git:
            repo: https://github.com/cat-in-136/redmine_hearts.git
            dest: "{{ pod_path }}/redmine/plugins/redmine_hearts"

        - name: searchable_selectbox
          ansible.builtin.git:
            repo: https://github.com/farend/redmine_searchable_selectbox.git
            dest: "{{ pod_path }}/redmine/plugins/redmine_searchable_selectbox"

        - name: issue_assign_notice
          ansible.builtin.git:
            repo: https://github.com/onozaty/redmine_issue_assign_notice.git
            dest: "{{ pod_path }}/redmine/plugins/redmine_issue_assign_notice"

        - name: theme changer
          ansible.builtin.git:
            repo: https://github.com/haru/redmine_theme_changer.git
            dest: "{{ pod_path }}/redmine/plugins/redmine_theme_changer"

      when: v == "v4"

    - name: Redmine Plugins install
      shell: |
        podman exec {{ redmine_name }} bundle install --jobs=4 --without development test && \
        podman exec {{ redmine_name }} bundle exec rake redmine:plugins:migrate RAILS_ENV=production && \
        podman restart {{ redmine_name }}

