
- hosts: ds9its11
  become: true
  become_method: sudo

  vars:
    pod_path: /data/red-pod/
    redmine_name: redmine

  tasks:
    - name: bleuclair
      ansible.builtin.git:
        repo: https://github.com/farend/redmine_theme_farend_bleuclair.git
        dest: "{{ pod_path }}/redmine/public/themes/bleuclair"

