
- hosts: ds9its11
  become: true
  become_method: sudo

  vars:
    pod_path: /data/red-pod2/
    redmine_name: redmine2

  tasks:
    - name: checklists confirm
      stat: path="{{ pod_path }}backup/plugins/redmine_checklists-3_1_21-light.zip"
      register: result1

    - name: checklists unzip
      unarchive:
        src: "{{ pod_path }}backup/plugins/redmine_checklists-3_1_21-light.zip"
        dest: "{{ pod_path }}redmine/plugins/"
      when: result1.stat.exists

    - name: Redmine Plugins install
      shell: |
        podman exec {{ redmine_name }} bundle install --jobs=4 --without development test && \
        podman exec {{ redmine_name }} bundle exec rake redmine:plugins:migrate RAILS_ENV=production && \
        podman restart {{ redmine_name }}

