
- hosts: ds9temp11
  become: true
  become_method: sudo

  vars:
    pod_path: /data/red-pod/
    DL_URL: https://drive.google.com/uc?export=download&id=xxxxxxxxxxxxxxxxxxxxxxxxxxxx
    CK_SUM: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    redmine_name: redmine

  tasks:
    - name: Cleanup
      file:
        path: "{{ pod_path }}redmine/plugins/"
        state: absent

    - name: Recriate Directory
      file: state=directory path={{ pod_path }}/redmine/plugins

    - name: checklist Download
      get_url:
        url: "{{ DL_URL }}"
        sha256sum: "{{ CK_SUM }}"
        force: True
        dest: "{{ pod_path }}backup/plugins/redmine_checklists-3_1_19-light.zip"

    - name: checklists unzip
      unarchive:
        src: "{{ pod_path }}backup/plugins/redmine_checklists-3_1_19-light.zip"
        dest: "{{ pod_path }}redmine/plugins/"

    - name: Tags & Hide Sidebar
      shell: |
        git clone https://github.com/ixti/redmine_tags.git && \
        git clone https://gitlab.com/bdemirkir/sidebar_hide.git
      args:
        chdir: "{{ pod_path }}/redmine/plugins/"

    - name: Redmine Plugins install
      shell: |
        podman exec {{ redmine_name }} bundle install --jobs=4 --without development test && \
        podman exec {{ redmine_name }} bundle exec rake redmine:plugins:migrate RAILS_ENV=production && \
        podman restart {{ redmine_name }}

