
- hosts: ds9its11
  become: true
  become_method: sudo

  vars:
    pod_path: /data/red-pod/
    redmine_name: redmine

  tasks:
    - name: checklists
      unarchive:
        src: "{{ pod_path }}/redmine/plugins/redmine_checklists-3_1_19-light.zip"
        dest: "{{ pod_path }}/redmine/plugins/"

    - name: Tags
      shell: |
        git clone https://github.com/ixti/redmine_tags.git
      args:
        chdir: "{{ pod_path }}/redmine/plugins/"

    - name: Redmine Plugins install
      shell: |
        podman exec {{ redmine_name }} bundle install --jobs=4 --without development test && \
        podman exec {{ redmine_name }} bundle exec rake redmine:plugins:migrate RAILS_ENV=production && \
        podman restart {{ redmine_name }}

