
- hosts: ds9its11
  become: true
  become_method: sudo

  vars:
    pod_path: /data/red-pod/
    redmine_name: redmine

  tasks:
    - name: checklists unzip
      unarchive:
        src: "{{ pod_path }}backup/plugins/redmine_checklists-3_1_19-light.zip"
        dest: "{{ pod_path }}redmine/plugins/"

    - name: People plugin unzip
      unarchive:
        src: "{{ pod_path }}backup/plugins/redmine_people-1_6_1-light.zip"
        dest: "{{ pod_path }}redmine/plugins/"

    - name: Tags
      ansible.builtin.git:
        repo: https://github.com/ixti/redmine_tags.git
        dest: "{{ pod_path }}/redmine/plugins/redmine_tags"

    - name: Hide Sidebar
      ansible.builtin.git:
        repo: https://gitlab.com/bdemirkir/sidebar_hide.git
        dest: "{{ pod_path }}/redmine/plugins/sidebar_hide"

    - name: issue template
      ansible.builtin.git:
        repo: https://github.com/agileware-jp/redmine_issue_templates.git
        dest: "{{ pod_path }}/redmine/plugins/redmine_issue_templates"

    - name: view customize plugin
      ansible.builtin.git:
        repo: https://github.com/onozaty/redmine-view-customize.git
        dest: "{{ pod_path }}/redmine/plugins/view_customize"

    - name: persist wiki format plugin
      ansible.builtin.git:
        repo: https://github.com/pinzolo/redmine_persist_wfmt.git
        dest: "{{ pod_path }}/redmine/plugins/redmine_persist_wfmt"

    - name: Redmine Plugins install
      shell: |
        podman exec {{ redmine_name }} bundle install --jobs=4 --without development test && \
        podman exec {{ redmine_name }} bundle exec rake redmine:plugins:migrate RAILS_ENV=production && \
        podman restart {{ redmine_name }}

