
- hosts: ds9its11
  become: true
  become_method: sudo

  vars:
    # env_id: 2
    pod_name: "red-pod{{ env_id }}"
    pod_path: /data/{{ pod_name }}/
    ht_name: httpd{{ env_id }}
    rd_name: redmine{{ env_id }}
    ms_name: mysql{{ env_id }}
    mm_name: memchached{{ env_id }}
    ht_port: "8{{ env_id }}80"
    rd_port: "30{{ env_id }}0"
    ms_port: "33{{ env_id }}6"
    # rd_image: docker.io/library/redmine:5.0.0-bullseye
    rd_image: docker.io/library/redmine:4-passenger
    ms_image: docker.io/library/mysql:5.7
    mm_image: docker.io/library/memcached:1.6.15-bullseye

  tasks:
    - name: mkdir {{ pod_name }}
      file: state=directory path={{ pod_path }}{{ item }}
      with_items:
        - mysql/data
        - mysql/conf/conf.d
        - mysql/logs
        - backup/db
        - backup/files
        - backup/plugins
        - backup/theme
        - redmine/files
        - redmine/conf
        - redmine/plugins
        - redmine/log
        - redmine/public/themes
        - redmine/git

    - name: Copy MySQL conf
      copy:
        src: "./conf/multibyte.cnf"
        dest: "{{ pod_path }}/mysql/conf/conf.d/"

    - name: Copy Redmine conf additional_environment.rb
      copy:
        src: "./conf/additional_environment.rb"
        dest: "{{ pod_path }}/redmine/conf/"

    - name: Copy Redmine conf configuration.yml
      copy:
        src: "./conf/configuration.yml"
        dest: "{{ pod_path }}/redmine/conf/"

    - name: Copy Redmine conf Gemfile.local
      copy:
        src: "./conf/Gemfile.local"
        dest: "{{ pod_path }}/redmine/conf/"

    - name: Podman Pod Create
      containers.podman.podman_pod:
        name: "{{ pod_name }}"
        state: created
        ports:
          - "{{ ht_port }}:80"
          - "{{ rd_port }}:3000"
          - "{{ ms_port }}:3306"
          #- 8080:80
          #- 3010:3000
          #- 3316:3306

    - name: Podman MySQL Contaner Run
      containers.podman.podman_container:
        name: "{{ ms_name }}"
        state: started
        image: "{{ ms_image }}"
        pod: "{{ pod_name }}"
        env:
          MYSQL_DATABASE: "redmine"
          MYSQL_ROOT_PASSWORD: "P@ss"
          MYSQL_USER: "user"
          MYSQL_PASSWORD: "secret"
        volume:
          - "{{ pod_path }}/mysql/data:/var/lib/mysql"
          - "{{ pod_path }}/mysql/conf/conf.d:/etc/mysql/conf.d"
          - "{{ pod_path }}/backup/db:/backup/db"

    - name: Podman Memchaced Contaner Run
      containers.podman.podman_container:
        name: "{{ mm_name }}"
        state: started
        image: "{{ mm_image }}"
        pod: "{{ pod_name }}"

    - name: Wait 60 seconds for port {{ ms_port }}
      wait_for:
        timeout: 60
        port: "{{ ms_port }}"
        host: 0.0.0.0

    - name: Podman Redmine Contaner Run
      containers.podman.podman_container:
        name: "{{ rd_name }}"
        state: started
        image: "{{ rd_image }}"
        pod: "{{ pod_name }}"
        env:
          REDMINE_DB_MYSQL: "127.0.0.1"
          REDMINE_DB_USERNAME: "user"
          REDMINE_DB_PASSWORD: "secret"
        volume:
          - "{{ pod_path }}/redmine/files:/usr/src/redmine/files"
          - "{{ pod_path }}/redmine/conf/additional_environment.rb:/usr/src/redmine/config/additional_environment.rb"
          - "{{ pod_path }}/redmine/conf/configuration.yml:/usr/src/redmine/config/configuration.yml"
          - "{{ pod_path }}/redmine/conf/Gemfile.local:/usr/src/redmine/Gemfile.local"
          - "{{ pod_path }}/redmine/plugins:/usr/src/redmine/plugins"
          - "{{ pod_path }}/redmine/log:/usr/src/redmine/log"
          - "{{ pod_path }}/redmine/public/themes:/usr/src/redmine/public/themes"
          - "{{ pod_path }}/redmine/git:/usr/src/redmine/git"

