
- hosts: ds9its11
  become: true
  become_method: sudo

  vars:
    env_id: 2
    pod_name: "red-pod{{ env_id }}"
    pod_path: /data/{{ pod_name }}/
    ht_name: httpd{{ env_id }}
    rd_name: redmine{{ env_id }}
    ms_name: mysql{{ env_id }}
    ht_port: 8280
    rd_port: 3020
    ms_port: 3326
    rd_image: docker.io/library/redmine:4-passenger
    ms_image: docker.io/library/mysql:5.7

  tasks:
    - name: mkdir {{ pod_name }}
      file: state=directory path={{ pod_path }}{{ item }}
      with_items:
        - mysql/data
        - mysql/conf/conf.d
        - mysql/logs
        - backup/db
        - backup/files
        - backup/plugins
        - redmine/files
        - redmine/plugins
        - redmine/log
        - redmine/public/themes
        - redmine/git

    - name: Copy MySQL conf
      copy:
        src: "./conf/multibyte.cnf"
        dest: "{{ pod_path }}/mysql/conf/conf.d/"

    - name: Podman Pod Create
      containers.podman.podman_pod:
        name: "{{ pod_name }}"
        state: created
        ports:
          - "{{ ht_port }}:80"
          - "{{ rd_port }}:3000"
          - "{{ ms_port }}:3306"
          #- 8080:80
          #- 3010:3000
          #- 3316:3306

    - name: Podman MySQL Contaner Run
      containers.podman.podman_container:
        name: "{{ ms_name }}"
        state: started
        image: "{{ ms_image }}"
        pod: "{{ pod_name }}"
        env:
          MYSQL_DATABASE: "redmine"
          MYSQL_ROOT_PASSWORD: "P@ss"
          MYSQL_USER: "user"
          MYSQL_PASSWORD: "secret"
        volume:
          - "{{ pod_path }}/mysql/data:/var/lib/mysql"
          - "{{ pod_path }}/mysql/conf/conf.d:/etc/mysql/conf.d"
          - "{{ pod_path }}/backup/db:/backup/db"

    - name: Wait 60 seconds for port {{ ms_port }}
      wait_for:
        timeout: 60
        port: "{{ ms_port }}"
        host: 0.0.0.0

    - name: Podman Redmine Contaner Run
      containers.podman.podman_container:
        name: "{{ rd_name }}"
        state: started
        image: "{{ rd_image }}"
        pod: "{{ pod_name }}"
        env:
          REDMINE_DB_MYSQL: "127.0.0.1"
          REDMINE_DB_USERNAME: "user"
          REDMINE_DB_PASSWORD: "secret"
        volume:
          - "{{ pod_path }}/redmine/files:/usr/src/redmine/files"
          - "{{ pod_path }}/redmine/plugins:/usr/src/redmine/plugins"
          - "{{ pod_path }}/redmine/log:/usr/src/redmine/log"
          - "{{ pod_path }}/redmine/public/themes:/usr/src/redmine/public/themes"
          - "{{ pod_path }}/redmine/git:/usr/src/redmine/git"

